### ISSUE TITLE
报错Cannot read properties of undefined (reading 'h')"

### ISSUE THREAD

**Issue by Check948** [linx4200/vue-color#258]
vue.runtime.esm.js:3049 TypeError: Cannot read properties of undefined (reading 'h')
    at r (vue-color.min.js:1:1)
    at VueComponent.data (vue-color.min.js:1:1)
    at getData (vue.runtime.esm.js:5464:1)
    at initData (vue.runtime.esm.js:5428:1)
    at initState (vue.runtime.esm.js:5369:1)
    at Vue._init (vue.runtime.esm.js:5691:1)
    at new VueComponent (vue.runtime.esm.js:5826:1)
    at createComponentInstanceForVnode (vue.runtime.esm.js:4544:1)
    at init (vue.runtime.esm.js:4406:1)
    at createComponent (vue.runtime.esm.js:6567:1)

为什么81版本会有这个报错

**Comment by Check948** [comment]
是

**Comment by hackerslizc** [comment]
解决了吗，同样的问题~

**Comment by codeLittleNewbie** [comment]
vue3好像不支持?

**Comment by H-J-CyberCitizen** [comment]
vue3 用不了，哭了

**Comment by codeLittleNewbie** [comment]
您好，你的邮件我已经收到，谢谢~~

**Comment by No2015** [comment]
@ckpack/vue-color

**Comment by zhaosiqi** [comment]
vue3 无法支持

**Comment by codeLittleNewbie** [comment]
您好，你的邮件我已经收到，谢谢~~

**Comment by codeLittleNewbie** [comment]
您好，你的邮件我已经收到，谢谢~~
